site_name: Getting Started with the WE1S Workspace
template_version: 1.0.0
workspace_version: 1.0.0
nav:
  - Introduction: index.md
  - How Jupyter Notebooks Work: how-jupyter-notebooks-work.md
  - Introduction to Python: introduction-to-python.md
  - Workspace Structure: workspace-structure.md
  - Creating a Project: creating-a-project.md
  - Modules:
      - modules/index.md
      - comparing: modules/comparing.md
      - counting: modules/counting.md
      - dendrogram: modules/dendrogram.md
      - dfr_browser: modules/dfr-browser.md
      - diagnostics: modules/diagnostics.md
      - export: modules/export.md
      - import: modules/import.md
      - json_utilities: modules/json-utilities.md
      - metadata: modules/metadata.md
      - pyldavis: modules/pyldavis.md
      - topic_bubbles: modules/topic-bubbles.md
      - topic_modeling: modules/topic-modeling.md
      - utilities: modules/utilities.md
  - Glossary: glossary.md
theme:
  favicon: img/we1s-logo-3stripes-transparent-25x26-1.png
  name: material
  custom_dir: overrides
  palette:
    - scheme: we1s
  icon:
    logo: we1s/we1s-logo-25x26-1-inverted
    repo: fontawesome/brands/github
markdown_extensions:
  - meta
  - admonition
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.keys
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
      options:
        custom_icons:
          - overrides/.icons
extra_css:
  - stylesheets/extra.css
extra_javascript:
  - javascripts/mark.es6.min.js
  - javascripts/extra.js
copyright: Copyright &copy; 2021- <a href="https://we1s.ucsb.edu" target="_blank">WE1S Project</a>
repo_url: https://github.com/whatevery1says
extra:
  social:
    - icon: fontawesome/solid/globe
      link: https://we1s.ucsb.edu
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/WE1Sproject
    - icon: fontawesome/brands/github
      link: https://github.com/whatevery1says
plugins:
    - search
    - macros
    - section-index

